# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test-linux
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest]
        container:
          - 'debian:8'
          - 'debian:9'
          - 'debian:10'
          - 'ubuntu:14.04'
          - 'ubuntu:16.04'
          - 'oraclelinux:6'
          - 'oraclelinux:7'
          - 'centos:6'
          - 'centos:7'
          - 'centos:8'
    
    steps:
    - uses: actions/checkout@v2 
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Alt Job
      run: python3 setup.py install

    - name: Test with scrapy check
      run: scrapy check goodwork.ca engages.ca arrondissement.com cdeacf.ca chantier.qc.ca enviroemplois.org 
